### ISSUE TITLE
Additional Options

### ISSUE THREAD

**Issue by ninjatacoshell** [osuchanglab/autoANI#1]
So far your autoANI script only runs a BLAST-based ANI (ANIb; see [Konstantinidis and Tiedje 2005](http://jb.asm.org/content/187/18/6258.abstract) and [Goris _et al_. 2007](http://ijs.microbiologyresearch.org/content/journal/ijsem/10.1099/ijs.0.64483-0)). Have you thought about including:
- a MUMmer-based ANI (ANIm; see [Richter and Rosselló-Móra 2009](http://www.pnas.org/content/106/45/19126.abstract)),
- tetranucleotide regression (TETRA; see [Teeling _et al_. 2004](http://onlinelibrary.wiley.com/wol1/doi/10.1111/j.1462-2920.2004.00624.x/abstract) and [Richter and Rosselló-Móra 2009](http://www.pnas.org/content/106/45/19126.abstract)), and
- average amino acid identity (AAI; see [Konstantinidis and Tiedje 2005](http://jb.asm.org/content/187/18/6258.abstract) and [Rodrigues and Konstantinidis 2014](http://enve-omics.gatech.edu/sites/default/files/2014-Rodriguez_R-Konstantinidis_Microbe_Magazine.pdf))?

**Comment by davised** [comment]
We agree that the addition of ANI alternatives to this tool would be nice.

Unfortunately, we don't have the resources to troubleshoot the addition of those pipelines to this tool at this time.

Thank you for the suggestions. If resources and/or time become available in the future, we will re-consider adding these calculations to the software.
